-- ============================================
-- Student Course Enrollment System
-- MySQL Database Schema
-- ============================================

CREATE DATABASE IF NOT EXISTS enrollment_system;
USE enrollment_system;

-- Students
CREATE TABLE IF NOT EXISTS students (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    email VARCHAR(150) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Admins
CREATE TABLE IF NOT EXISTS admins (
    id INT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(100) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Courses
CREATE TABLE IF NOT EXISTS courses (
    id INT AUTO_INCREMENT PRIMARY KEY,
    code VARCHAR(20) NOT NULL UNIQUE,
    title VARCHAR(150) NOT NULL,
    description TEXT,
    instructor VARCHAR(100) NOT NULL,
    credits INT NOT NULL DEFAULT 3,
    capacity INT NOT NULL DEFAULT 30,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Enrollments (junction table)
CREATE TABLE IF NOT EXISTS enrollments (
    id INT AUTO_INCREMENT PRIMARY KEY,
    student_id INT NOT NULL,
    course_id INT NOT NULL,
    enrolled_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (student_id) REFERENCES students(id) ON DELETE CASCADE,
    FOREIGN KEY (course_id) REFERENCES courses(id) ON DELETE CASCADE,
    UNIQUE KEY unique_enrollment (student_id, course_id)
);

-- Default admin login -> username: admin | password: admin123
-- (hash is generated by backend/database/seed-admin.js — run it once after setup)

-- Sample courses to get started
INSERT INTO courses (code, title, description, instructor, credits, capacity) VALUES
('CS101', 'Introduction to Programming', 'Fundamentals of programming using Python. Covers variables, control flow, functions and basic data structures.', 'Dr. Anita Rao', 4, 40),
('CS205', 'Data Structures & Algorithms', 'In-depth study of arrays, linked lists, trees, graphs, and algorithm design techniques.', 'Prof. Karthik Iyer', 4, 35),
('MA110', 'Discrete Mathematics', 'Logic, set theory, combinatorics, and graph theory for computer science applications.', 'Dr. Meera Nair', 3, 45),
('EE150', 'Digital Electronics', 'Boolean algebra, logic gates, combinational and sequential circuits.', 'Prof. Suresh Kumar', 3, 30),
('CS310', 'Database Management Systems', 'Relational model, SQL, normalization, transactions, and database design.', 'Dr. Anita Rao', 4, 35)
ON DUPLICATE KEY UPDATE title = VALUES(title);
